// Generates lib/schema-types.ts from schema/. The JSON Schema is the single
// source of truth for a run record: ajv validates the data against it, and
// these types are derived from it, so data, schema and types cannot disagree.
// CI regenerates and fails on a diff, exactly like data/benchmarks.json.
//
//   node scripts/generate-types.mjs
//
// Deliberately not a general JSON Schema compiler: it understands only the
// constructs these two schemas use, and throws on anything else rather than
// silently emitting `any`.

import { readFileSync, writeFileSync } from "node:fs";
import { basename, dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(ROOT, "lib", "schema-types.ts");

const TARGETS = [
  { file: "benchmark.schema.json", name: "BenchmarkRecord" },
  { file: "index.schema.json", name: "BenchmarkIndex" },
];

// Enums worth a name of their own; anything else is emitted inline.
const ENUM_ALIASES = { status: "BenchmarkStatus", gpuVendor: "GpuVendor" };

const schemas = TARGETS.map((t) => ({
  ...t,
  schema: JSON.parse(readFileSync(join(ROOT, "schema", t.file), "utf8")),
}));

const nameForRef = (ref) => {
  const target = schemas.find((s) => basename(ref) === s.file);
  if (!target) throw new Error(`$ref points outside schema/: ${ref}`);
  return target.name;
};

const union = (values) => values.map((v) => JSON.stringify(v)).join(" | ");

function tsType(prop, key) {
  if (prop.$ref) return nameForRef(prop.$ref);
  if (prop.enum) return ENUM_ALIASES[key] ?? union(prop.enum);
  switch (prop.type) {
    case "string":
      return "string";
    case "number":
    case "integer":
      return "number";
    case "boolean":
      return "boolean";
    case "array":
      if (!prop.items) throw new Error(`array without items: ${key}`);
      return `${tsType(prop.items, key)}[]`;
    default:
      throw new Error(`unsupported schema type for "${key}": ${JSON.stringify(prop.type)}`);
  }
}

const lines = [
  "// Generated by scripts/generate-types.mjs from schema/. Do not edit by hand:",
  "// change the JSON Schema and rerun `npm run generate:types`.",
  "",
];

const screamingSnake = (name) => name.replace(/([a-z0-9])([A-Z])/g, "$1_$2").toUpperCase();

// Named enum aliases, plus the value list so nothing has to restate it in TS.
for (const [key, name] of Object.entries(ENUM_ALIASES)) {
  const owner = schemas.find((s) => s.schema.properties?.[key]?.enum);
  if (!owner) throw new Error(`no schema declares an enum for "${key}"`);
  const values = owner.schema.properties[key].enum;
  lines.push(
    `export type ${name} = ${union(values)};`,
    "",
    `export const ${screamingSnake(name)}_VALUES: readonly ${name}[] = [${values
      .map((v) => JSON.stringify(v))
      .join(", ")}];`,
    ""
  );
}

function emitInterface(name, schema, { widenEnums = false } = {}) {
  const required = new Set(schema.required ?? []);
  lines.push(`export interface ${name} {`);
  for (const [key, prop] of Object.entries(schema.properties)) {
    if (prop.description && !widenEnums) lines.push(`  /** ${prop.description} */`);
    const safeKey = /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(key) ? key : JSON.stringify(key);
    const type = widenEnums && prop.enum ? "string" : tsType(prop, key);
    lines.push(`  ${safeKey}${required.has(key) ? "" : "?"}: ${type};`);
  }
  lines.push("}", "");
}

for (const { name, file, schema } of schemas) {
  if (schema.description) lines.push(`/** ${schema.description} */`);
  emitInterface(name, schema, {});

  // The same shape as it comes out of JSON: TypeScript widens string literals
  // when importing a .json file, so the enum-valued fields arrive as `string`
  // and have to be narrowed once, at the edge.
  if (file === "benchmark.schema.json") {
    lines.push(
      `/** ${name} as imported from JSON: enum fields not yet narrowed. */`
    );
    emitInterface(`Raw${name}`, schema, { widenEnums: true });
  }
}

writeFileSync(OUT, lines.join("\n").replace(/\n+$/, "\n"));
console.log(`wrote lib/schema-types.ts (${schemas.map((s) => s.name).join(", ")})`);
