import CountTo from "../CountTo";
import { aggregateContributors, aggregateModels, allRecords, DISCORD_URL, hardwareSlices, runActivity } from "../../lib/data";
import { SectionHead } from "../ui";

export default function Community() {
  const contributors = aggregateContributors();
  const models = new Set(allRecords().map((r) => r.model)).size;
  const hardware = hardwareSlices();
  const totalRuns = allRecords().length;
  const maxHw = hardware[0]?.count ?? 1;
  const activity = runActivity();
  const maxActivity = Math.max(1, ...activity.map((day) => day.count));

  return (
    <section className="border-b border-ink/25">
      <div className="mx-auto w-full max-w-page px-6 py-20 md:px-10 lg:py-24">
        <SectionHead no="SEC.07 / NETWORK" title="RUN BY CONTRIBUTORS, NOT BY A COMPANY" note="YOU ARE THE INSTRUMENT FLEET" />

        <div className="mt-12 grid gap-12 lg:grid-cols-[1.2fr_1fr]">
          {/* contribution block */}
          <div>
            <div className="flex items-center justify-between">
              <span className="mono text-[0.5625rem] tracking-[0.26em] text-stone">MEASURED RUN ACTIVITY — 84 DAYS</span>

            </div>
            <div className="mt-4 flex h-24 items-end gap-1 border border-ink/30 bg-paper-dim/70 p-3" data-reveal role="img" aria-label="Measured benchmark runs per day">
              {activity.map((day) => (
                <span key={day.date} title={`${day.date}: ${day.count} run${day.count === 1 ? "" : "s"}`} className="min-w-0 flex-1 bg-ink/70" style={{ height: `${Math.max(day.count ? 8 : 2, (day.count / maxActivity) * 100)}%` }} />
              ))}
            </div>
            <div className="mono mt-2 flex items-center justify-between text-[0.5625rem] tracking-[0.18em] text-stone">
              <span>{activity[0]?.date ?? "NO DATA"}</span>
              <span>MEASURED RUNS / DAY</span>
              <span>{activity.at(-1)?.date ?? "NO DATA"}</span>
            </div>

            {/* stats */}
            <div className="mt-10 grid grid-cols-2 gap-px border border-ink/30 bg-ink/20 sm:grid-cols-4">
              {[
                { v: contributors.length, label: "CONTRIBUTORS" },
                { v: totalRuns, label: "RUNS INDEXED" },
                { v: models, label: "MODELS" },
                { v: hardware.length, label: "HARDWARE CONFIGS" },
              ].map((s, i) => (
                <div key={s.label} className="bg-paper p-5" data-reveal style={{ "--reveal-delay": `${i * 80}ms` } as React.CSSProperties}>
                  <span className="font-disp block text-3xl font-extrabold md:text-4xl">
                    <CountTo value={s.v} />
                  </span>
                  <span className="mono mt-1 block text-[0.5625rem] tracking-[0.2em] text-stone">{s.label}</span>
                </div>
              ))}
            </div>
          </div>

          {/* hardware distribution */}
          <div>
            <span className="mono text-[0.5625rem] tracking-[0.26em] text-stone">RUNS BY HARDWARE</span>
            {hardware.length ? (
              <ul className="mono mt-4 space-y-2.5 text-[0.6875rem]">
                {hardware.map((h, i) => (
                  <li key={h.hardware} className="flex items-center gap-3" data-reveal style={{ "--reveal-delay": `${i * 50}ms` } as React.CSSProperties}>
                    <span className="w-40 shrink-0 truncate tracking-[0.08em] text-graphite sm:w-44">{h.hardware.toUpperCase()}</span>
                    <span className="relative h-[9px] flex-1 bg-paper-dark" aria-hidden>
                      <span className="bar-fill" style={{ "--fill": h.count / maxHw } as React.CSSProperties} />
                    </span>
                    <span className="clip-numeric w-6 text-right">{h.count}</span>
                  </li>
                ))}
              </ul>
            ) : (
              <p className="mt-4 border border-ink/20 bg-paper-dim/50 p-5 mono text-[0.625rem] tracking-[0.16em] text-stone">
                NO MEASURED HARDWARE RUNS YET.
              </p>
            )}

            <div className="mt-8 border border-ink/30 bg-paper-dim/60 p-5">
              <p className="mono text-[0.5625rem] tracking-[0.26em] text-stone">NOTE</p>
              <p className="mt-2 text-sm leading-relaxed text-graphite">
                Counts above are calculated from measured records in <span className="mono text-[0.8125rem]">results/</span> and regenerated by CI — no self-reported totals.
              </p>
            </div>

            <div className="mt-8 border border-ink/40 bg-paper p-5">
              <p className="mono text-[0.5625rem] tracking-[0.26em] text-stone">COORDINATION</p>
              <p className="mt-2 text-sm leading-relaxed text-graphite">
                No company runs this. Rigs are coordinated, runs are compared and
                results get verified over Discord — join the network and put your
                hardware on the index.
              </p>
              <a
                href={DISCORD_URL}
                target="_blank"
                rel="noopener noreferrer"
                className="btn btn-solid mt-4"
              >
                JOIN THE DISCORD ↗
              </a>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
